language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install ./src/metriqueu --use-mirrors"
  - "pip install ./src/metrique --use-mirrors"
  - "pip install ./src/metriqued --use-mirrors"
  - "pip install ./src/metriquec --use-mirrors"
# command to run tests
script: nosetests
